
export enum CategorieArticle {
  POLITIQUE = 'POLITIQUE',
  ECONOMIE = 'ECONOMIE',
  TECHNOLOGIE = 'TECHNOLOGIE',
  SPORT = 'SPORT',
  CULTURE = 'CULTURE',
  SANTE = 'SANTE',
  EDUCATION = 'EDUCATION',
  ENVIRONNEMENT = 'ENVIRONNEMENT',
  INTERNATIONAL = 'INTERNATIONAL',
  SOCIETE = 'SOCIETE',
  SCIENCE = 'SCIENCE',
  SECURITE = 'SECURITE',
  DIVERTISSEMENT = 'DIVERTISSEMENT',
  AUTRE = 'AUTRE',
}