export enum TypeEvenement {
  SPORTIF = 'SPORTIF',
  CULTUREL = 'CULTUREL',
  POLITIQUE = 'POLITIQUE',
  ECONOMIQUE = 'ECONOMIQUE',
  SOCIAL = 'SOCIAL',
  TECHNOLOGIQUE = 'TECHNOLOGIQUE',
  SCIENTIFIQUE = 'SCIENTIFIQUE',
  EDUCATION = 'EDUCATION',
  MEDIATIQUE = 'MEDIATIQUE',
  ASSOCIATIF = 'ASSOCIATIF',
  AUTRE = 'AUTRE',
}